### ISSUE TITLE
Getting java.lang.IndexOutOfBoundsException with latest release

### ISSUE THREAD

**Issue by Infinitay** [ArtificialPB/DevelopmentKit#1]
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException
	at com.artificial.cachereader.DataSource.readSectorData(DataSource.java:158)
	at com.artificial.cachereader.DataSource.readSector(DataSource.java:143)
	at com.artificial.cachereader.DataSource.readArchive(DataSource.java:124)
	at com.artificial.cachereader.fs.CacheType.getArchiveData(CacheType.java:46)
	at com.artificial.cachereader.fs.CacheType.getArchive(CacheType.java:31)
	at com.artificial.cachereader.wrappers.rt4.loaders.ItemDefinitionLoader.<init>(ItemDefinitionLoader.java:9)
	at com.artificial.cachereader.fs.RT4CacheSystem.<init>(RT4CacheSystem.java:20)
	at com.artificial.developmentkit.GameTypeSelectionPanel.osrsButtonActionPerformed(GameTypeSelectionPanel.java:33)
	at com.artificial.developmentkit.GameTypeSelectionPanel.lambda$initComponents$1(GameTypeSelectionPanel.java:80)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ArtificialPB** [comment]
Not much changed since the last release and it seems to work fine for me @Infinitay 

Please make sure your cache is not corrupted by deleting it and re-running the game client.

**Comment by Infinitay** [comment]
`Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -2
	at com.artificial.cachereader.wrappers.rt4.loaders.ItemDefinitionLoader.fixItem(ItemDefinitionLoader.java:27)
	at com.artificial.cachereader.wrappers.rt4.loaders.ItemDefinitionLoader.load(ItemDefinitionLoader.java:17)
	at com.artificial.cachereader.wrappers.rt4.loaders.ItemDefinitionLoader.load(ItemDefinitionLoader.java:7)
	at com.artificial.developmentkit.DevelopmentKit.loadDefinitions(DevelopmentKit.java:111)
	at com.artificial.developmentkit.DevelopmentKit.<init>(DevelopmentKit.java:37)
	at com.artificial.developmentkit.DevelopmentKitMain.lambda$main$1(DevelopmentKitMain.java:44)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Process finished with exit code 1
`

Anything I can do to fix this? I already tried deleting my cache

**Comment by ArtificialPB** [comment]
This is a bug on my end @Infinitay. Will be fixed with next version
